### ISSUE TITLE
Missing description under title

### ISSUE THREAD

**Issue by lfarah** [dhirajjadhao/Newly#2]
<img width="437" alt="screen shot 2016-12-08 at 10 52 55 pm" src="https://cloud.githubusercontent.com/assets/6511079/21040328/14f49554-bd99-11e6-9334-47409020cc08.png">

**Comment by dhirajjadhao** [comment]
@lfarah Updated description, thanks for notifying. This project is open for new update request so let me know if you find any room for updates.
