### ISSUE TITLE
Why do you have a requirement of iOS 10+ ?

### ISSUE THREAD

**Issue by iGranDav** [dhirajjadhao/Newly#3]
An iOS 9+ requirement would be less restricting, and I don't see any iOS 10 only API in your code (I probably missed it 🙂 )

**Comment by dhirajjadhao** [comment]
@iGranDav Absolutely there is nothing specific to iOS 10, just missed it, thanks for pointing out. Will update it soon

**Comment by iGranDav** [comment]
@dhirajjadhao Now there is PR for that 🙂

**Comment by dhirajjadhao** [comment]
Thanks @iGranDav, merged and released
